# General Jekyll Config
markdown: kramdown
highlighter: pygments
url: http://uasi.github.io
lsi: false
exclude: [LICENSE, README.md, .gitignore, vendor]
timezone: Asia/Tokyo

# Theme customization
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: uasi
    bitbucket: uasi
    twitter: uasi

  name: uasi.github.io
  email: uasi@uasi.jp
  tagline: "Simplicity wins. Readability counts."

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
